### ISSUE TITLE
CreateInviteResponse throwing error with no expiration invites.

### ISSUE THREAD

**Issue by swiftyspiffy** [Baggykiin/Curse.NET#3]
I don't believe the CreateInviteResponse model is accounting for invites created without an expiration. When I create an invite with no expiration (0 minutes), the DateExpires field in the json response is an empty string, and I don't think JsonConverter is happy with this. Please see the image below (it has some data redacted):

![image](http://swfty.xyz/?id=484Hpf570)

Please see that DateExpires is an empty string, so JsonConvert fails. I'm not exactly sure how you want to handle this.

**Comment by swiftyspiffy** [comment]
For initial discovery info, see a23bcbcc56a6be2b6fa7bca3cedd4f25dc8e9ecd comments.

**Comment by geluk** [comment]
Technically the API shouldn't be returning an empty string here, but there's little we can do about that.

Because of this, it's probably best to extend ReadJson() in https://github.com/Baggykiin/Curse.NET/blob/master/Curse.NET/MicrosecondEpochConverter.cs#L34 to handle this. Probably a check on `objectType` to see if it's a string, and if that's the case, a check on `reader.Value` to confirm that it's an empty string, in which case `DateTime.MinValue` should probably be returned.
